### ISSUE TITLE
Error when run ng serve with --aot

### ISSUE THREAD

**Issue by abalad** [tb/ng2-gravatar#15]
```
Date: ERROR in ./node_modules/ng2-gravatar-directive/src/gravatar.directive.ts2017-12-05T00:33:17.307Z

Hash: 3bf44b1a49249c7441d8Module build failed: Error: E:\Projetos\OtiSEG\Cliente\node_modules\ng2-gravatar-directive\src\gravatar.directive.ts is not part of the compilation output. Please check the other error messages for details.

   at AngularCompilerPlugin.getCompiledFile (E:\Projetos\OtiSEG\Cliente\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:629:23)chunk {
inline}     at plugin.done.then (E:\Projetos\OtiSEG\Cliente\node_modules\@ngtools\webpack\src\loader.js:467:39)inline.bundle.js
 (inline) 5.79 kB     at process._tickCallback (internal/process/next_tick.js:109:7)[entry]
 [rendered]
 @ ./node_modules/ng2-gravatar-directive/src/index.js 6:9-40chunk {main
} main.bundle.js @ ./src/app/shared/parts/parts.module.ts (main) 1.02 MB 
[initial] @ ./src/app/dashboard/dashboard.module.ts [rendered]

chunk { @ ./src/app/app.module.tspolyfills
} polyfills.bundle.js @ ./src/main.ts (polyfills) 959 kB 
[initial] [rendered] @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

chunk {stylesERROR in ./node_modules/ng2-gravatar-directive/src/gravatar.module.ts} 
styles.bundle.js (styles) 4.15 MB [initial]Module build failed: Error: E:\Projetos\OtiSEG\Cliente\node_modules\ng2-gravatar-directive\src\gravatar.module.ts is not part of the compilation output. Please check the other error messages for details. [rendered]

chunk {    at AngularCompilerPlugin.getCompiledFile (E:\Projetos\OtiSEG\Cliente\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:629:23)vendor} 
vendor.bundle.js    at plugin.done.then (E:\Projetos\OtiSEG\Cliente\node_modules\@ngtools\webpack\src\loader.js:467:39) (vendor) 15.8 MB [initial]
 [rendered]    at process._tickCallback (internal/process/next_tick.js:109:7)

 @ ./node_modules/ng2-gravatar-directive/src/index.js 7:9-37
 @ ./src/app/shared/parts/parts.module.ts
 @ ./src/app/dashboard/dashboard.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

webpack: Failed to compile.
```

**Comment by techn1fire** [comment]
I'm having this same error without aot..
